import type { MotionPersonality } from './types.js';

/**
 * Hand-written prose snippets per preset. Loaded by section. Keeping these
 * static (rather than runtime-generated by a model) so the DESIGN.md output is
 * deterministic across builds and CI snapshot tests stay stable.
 */

export interface PresetProse {
  /** One paragraph for the Overview section. Brand voice. */
  overview: string;
  /** Motion personality classification. Drives the Motion section. */
  motionPersonality: MotionPersonality;
  /** One sentence describing the density / element rhythm. */
  density: string;
}

const FALLBACK: PresetProse = {
  overview:
    'A token-driven design system from the Arcana UI library. Three-tier tokens (primitive, semantic, component) compose into 108+ React components. Every visual property is theme-able through a single JSON file.',
  motionPersonality: 'default',
  density:
    'Comfortable density: 16px base spacing, 44px minimum touch targets, 1.5 line-height for body text.',
};

const PRESETS: Record<string, PresetProse> = {
  'arcana-light': {
    overview:
      'Light is the default Arcana preset. A clean neutral palette with a single indigo accent, sized for productivity dashboards and marketing surfaces alike. Comfortable density, generous whitespace, and a soft elevation system that reads as crafted rather than ornamental.',
    motionPersonality: 'default',
    density:
      'Comfortable density: 16px base spacing, 44px minimum touch targets, body text at 1.5 line-height.',
  },
  'arcana-dark': {
    overview:
      'Dark is the night-mode counterpart to Light. Same accent tokens, same density rhythm, recalibrated luminance so accent-on-surface pairs clear WCAG AA at body size. Built for long sessions; muted enough that focus rings still pop.',
    motionPersonality: 'default',
    density:
      'Comfortable density: 16px base spacing, 44px minimum touch targets, body text at 1.5 line-height.',
  },
  'arcana-midnight': {
    overview:
      'Midnight is for premium, finance-grade interfaces. Deep navy backgrounds carry soft gold accents; the palette evokes Bloomberg terminals and overnight trading desks. Dense data layouts stay legible because every accent / surface pair is contrast-verified against WCAG AA.',
    motionPersonality: 'calm',
    density:
      'Compact-leaning: tighter spacing on data rows, 14px base body text, generous gutters between dashboard regions.',
  },
  'arcana-terminal': {
    overview:
      'Terminal is a monospace-first preset for developer tooling, REPLs, and CLIs. The palette is intentionally small: foreground, background, an accent for prompts, a destructive for errors. Typography does the heavy lifting; chrome is minimal.',
    motionPersonality: 'snappy',
    density:
      'Compact density: 12px base body text in monospace, 4px spacing increments, no superfluous chrome around content.',
  },
  'arcana-retro98': {
    overview:
      'Retro98 reproduces the Windows 95 / Chicago aesthetic without irony. Beveled buttons, hard 1px borders, system gray backgrounds, and an MS Sans Serif equivalent for body text. Built for skeuomorphism comebacks and nostalgia-driven indie products.',
    motionPersonality: 'step',
    density:
      'Comfortable density tuned for fixed-pixel layouts: 16px base, hard borders instead of shadows.',
  },
  'arcana-glass': {
    overview:
      'Glass is a blurred-translucent preset for content-forward apps. Layers stack via backdrop-filter rather than solid surfaces; accents glow softly. Best on high-contrast wallpapers or hero imagery; falls back to a flat dark on browsers without backdrop-filter.',
    motionPersonality: 'languid',
    density:
      'Spacious density: 20px base spacing, 1.625 line-height for body, larger touch targets to compensate for low-contrast borders.',
  },
  'arcana-brutalist': {
    overview:
      'Brutalist is the anti-skin preset. Zero radii, zero shadows, motion disabled at the component level. Blocks of solid color, hard typography, system-default fonts. For experimental, editorial, or art-directed surfaces where the design system should disappear.',
    motionPersonality: 'static',
    density:
      'Comfortable density on a strict grid: 16px base, no rounding, no transition between states.',
  },
  'arcana-corporate': {
    overview:
      'Corporate is the safe-pick preset for B2B SaaS. Conservative neutrals, a single brand accent, predictable spacing. The version of Arcana you ship to enterprise clients who need it to look and feel familiar before they trust it to do something new.',
    motionPersonality: 'default',
    density: 'Comfortable density: 16px base, 44px touch targets, professional rhythm.',
  },
  'arcana-startup': {
    overview:
      'Startup is the marketing-forward preset for early-stage product surfaces. Brighter accents, larger headline scale, more confident shadow elevation. Reads as kinetic without being noisy.',
    motionPersonality: 'snappy',
    density:
      'Comfortable density with marketing-scale headline sizes; body text remains at 16px for readability.',
  },
  'arcana-editorial': {
    overview:
      'Editorial is calm, prose-first, and zero-radius. Built for long-form reading: news, magazines, essay platforms. Generous line-height, restrained accents, typography sized for sustained attention rather than scanning.',
    motionPersonality: 'calm',
    density:
      'Spacious density: 20px base spacing, 1.625-1.75 line-height for body, narrow content column for prose.',
  },
  'arcana-commerce': {
    overview:
      'Commerce is luxe, product-forward, and conversion-tuned. High-resolution imagery sits next to taut typography; CTAs are unmistakable; price displays use a tabular variant. Ships paired with the Forma demo at ecommerce.arcana-ui.com.',
    motionPersonality: 'default',
    density:
      'Comfortable density with product-card-aware grid spacing; tabular numerals on prices.',
  },
  'arcana-nature': {
    overview:
      'Nature uses an organic, earth-derived palette: clay, moss, sand, bark. Motion is spring-eased and slightly elongated to feel breathed. Best for sustainability brands, outdoor / wellness products, and content where warmth is a feature.',
    motionPersonality: 'organic',
    density:
      'Comfortable density: 16px base, generous shoulders on cards, soft 8px radii throughout.',
  },
  'arcana-neon': {
    overview:
      'Neon is the high-energy, after-dark preset. Saturated accents on near-black backgrounds, spring-eased transitions, generous glow on focus rings. Built for gaming, music, and creative tools where the interface earns its volume.',
    motionPersonality: 'spring',
    density:
      'Comfortable density with kinetic motion: 16px base, snappy transitions, focus rings that pop.',
  },
  'arcana-mono': {
    overview:
      'Mono is utilitarian and deliberately quiet. Single sans family, two grays plus an accent, no shadows. For internal tooling, status pages, and admin surfaces where function comes before identity.',
    motionPersonality: 'default',
    density: 'Comfortable density: 16px base, minimal chrome, focus on content over container.',
  },
};

export function getPresetProse(presetName: string): PresetProse {
  return PRESETS[presetName] ?? FALLBACK;
}

export function describeMotionPersonality(personality: MotionPersonality): string {
  switch (personality) {
    case 'calm':
      return 'Calm: durations slightly longer than default, easings lean ease-in-out. Reveals settle rather than snap.';
    case 'snappy':
      return 'Snappy: shorter durations, sharper easings. Interactions confirm immediately; nothing lingers.';
    case 'static':
      return 'Static: motion is disabled at the component level. Hover and focus states use color only, no transition.';
    case 'spring':
      return 'Spring: cubic-bezier easings overshoot the target slightly before settling. Reads as kinetic.';
    case 'step':
      return 'Step: easings use steps() for a chunky, retro feel. Transitions appear in discrete frames rather than smoothly.';
    case 'organic':
      return 'Organic: spring easings paired with slightly elongated durations. Motion feels breathed rather than mechanical.';
    case 'languid':
      return 'Languid: longer durations, ease-in-out only. Best for content-forward interfaces with translucent surfaces.';
    default:
      return 'Default: balanced durations and easings. Suitable for productivity and marketing surfaces alike.';
  }
}
